language: node_js

node_js:
  - node
  - lts/*
  - 8
  - 7
  - 6

os:
  - linux
  - osx

before_install:
  - npm i -g npm      # upgrade npm to the latest version

install:
  - npm ci

script:
  - npm run lint
  - npm test
